version: '3.3'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    links:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ${GRAFANA_ROOT}/configs/grafana.ini:/etc/grafana/grafana.ini
      - ${GRAFANA_ROOT}/data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    links:
      - alertmanager
      - node-exporter
    ports:
      - "9090:9090"
    volumes:
      - ${PROMETHEUS_ROOT}/configs:/etc/prometheus/configs
      - ${PROMETHEUS_ROOT}/data:/prometheus
    command:
      - "--config.file=/etc/prometheus/configs/prometheus.yml"
      - "--web.enable-lifecycle"
      - "--web.external-url=http://${HOSTNAME}:9090"

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - ${ALERTMANAGER_ROOT}/configs:/etc/alertmanager/configs
      - ${ALERTMANAGER_ROOT}/data:/alertmanager
    command:
      - "--config.file=/etc/alertmanager/configs/alertmanager.yml"
      - "--web.external-url=http://${HOSTNAME}:9090"

  node-exporter:
    privileged: true
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^/(rootfs/)?(dev|etc|host|proc|run|sys|volume1)($$|/)"

  prometheus-auto-reloader:
    image: billykwooten/prometheus_reloader
    container_name: prometheus_reloader
    restart: always
    volumes:
      - ${PROMETHEUS_ROOT}/configs:/mnt
    command:
      - "http://prometheus:9090/-/reload"
      - "/mnt/prometheus.yml"
      - "/mnt/prometheus.rules"
